apiVersion: v1
kind: Pod
metadata:
  name: hw-kubernetes-nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.20
      livenessProbe:
          httpGet:
            path: /
            port: 8555
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      ports:
      - name: http
        containerPort: 8555
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-kubernetes-image
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: hw-kubernetes-image
        image: hwkubernetes
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: hw-kubernetes-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8555
    targetPort: 8555
    nodePort: 30001